import Head from 'next/head'


const BalancePage = () => {
    return (
        <>
            <Head>
                <title>Balance</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p>Balance page</p>
        </>
    )
}
export default BalancePage