import Head from 'next/head'
import {Inter} from 'next/font/google'
import AuthPage from "@/pages/Auth";
import axios from "axios";
import {useEffect, useState} from "react";
import {useSelectorWithType} from "@/hooks/useSelectorWithType";

const token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR3MTI0ZXQyM2p3dEBnbWFpbC5jb20iLCJpYXQiOjE2ODU4MTY5NjQsImV4cCI6MTY4NTg3MDk2NH0.e92aUYWZqTgp546xF9oEfb24tINRiYb8Om2UkA6MUOM"
const Main = ({test}) => {
    if (!test) {
        return <div>Loading ...</div>
    }
    // const {isAuth} = useSelectorWithType(state => state.auth)
    const [balance, setBalance] = useState(0)
    const tempFetch = () => {
        const res = axios.get('http://localhost:3002/api/balance/get', {
            headers: {
                Authorization: token
            }
        }).then(res => {
            setBalance(res.data)
            console.log("res", res)
        })
        console.log(test)

    }

    useEffect(() => {
        console.log("enter")
    }, [])


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <p>Main after auth</p>
            <button onClick={tempFetch}>Get balance</button>
            <div>Balance from client{balance}</div>
            <div>Balance from getServerSideProps {test}</div>
        </>
    )
}

// export async function getServerSideProps() {
//     // try {
//     const data = await axios.get('http://localhost:3002/api/balance/get', {
//         headers: {
//             Authorization: token
//         }
//     })
//     return {
//         props: {
//             test: data.data
//         }
//     };
//     // } catch (e) {
//     //     return {
//     //         redirect: {
//     //             destination: '/rsdtd',
//     //             permanent: false,
//     //         },
//     //     };
//     // }
//
//
// }

export default Main