import Head from 'next/head'
import {Inter} from 'next/font/google'
import {useDispatch, useSelector} from "react-redux";
import {register} from "@/store/reducers/authReducer";
import React from "react";
import {useSelectorWithType} from "@/hooks/useSelectorWithType";
import AuthPage from "@/pages/Auth";

const inter = Inter({subsets: ['latin']})

export default function Home(){


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AuthPage />
        </>
    )
}