import Head from 'next/head'
import {Inter} from 'next/font/google'
import React, {useEffect} from "react";
import AuthPage from "@/pages/Auth";
import {useSelectorWithType} from "@/hooks/useSelectorWithType";
import {useRouter} from "next/router";
import {useDispatchWithType} from "@/hooks/useDispatchWithType"
import {checkAuthThunk} from "@/store/reducers/authReducer";
import CheckAuthLoadingLayout from "@/components/CheckAuthLoading";

const inter = Inter({subsets: ['latin']})


const Home = () => {
    const router = useRouter()
    const dispatch = useDispatchWithType()
    const {isAuth,isCheckingAuth} = useSelectorWithType(state => state.auth)

    useEffect(() => {
        dispatch(checkAuthThunk())
    }, [])
    useEffect(() => {
        if (isAuth && !isCheckingAuth) router.push('/Main')
    }, [isAuth,isCheckingAuth])
    console.log("/Auth ", isCheckingAuth,isAuth)
    if (isCheckingAuth || isAuth){
        return <CheckAuthLoadingLayout/>
    }


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AuthPage/>
        </>
    )
}
export default Home